version: 2

models:
  - name: stg_users
    description: Staging layer for users
    columns:
      - name: user_id
        description: Unique user identifier
        tests:
          - unique
          - not_null
      - name: age
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 150
      - name: email
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "LIKE '%@%'"
              config:
                severity: warn

  - name: stg_order_items
    description: Cleaned and standardized order items data
    columns:
      - name: order_item_id
        description: Unique order item identifier
        tests:
          - unique
          - not_null
      
      - name: order_id
        description: Foreign key to orders
        tests:
          - not_null
          - relationships:
              config:
                severity: error
              arguments:
                to: ref('stg_orders')
                field: order_id
      
      - name: product_id
        description: Foreign key to products
        tests:
          - not_null
          - relationships:
              config:
                severity: error
              arguments:
                to: ref('stg_products')
                field: product_id
      
      - name: quantity
        description: Quantity ordered
        tests:
          - not_null
      
      - name: sale_price
        description: Sale price at time of order
        tests:
          - not_null

  - name: stg_products
    description: Cleaned and standardized product data
    columns:
      - name: product_id
        description: Unique product identifier
        tests:
          - unique
          - not_null
      
      - name: product_name
        description: Product name
        tests:
          - not_null
      
      - name: category
        description: Product category
        tests:
          - not_null
      
      - name: price
        description: Product price
        tests:
          - not_null

  - name: stg_orders
    description: Cleaned and standardized orders data
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      
      - name: user_id
        description: Foreign key to users
        tests:
          - not_null
          - relationships:
              config:
                severity: error
              arguments:
                to: ref('stg_users')
                field: user_id
      - name: order_amount
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000