version: 2
models:
  - name: user_orders_summary
    description: User-level order summary for marketing analysis
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
          - relationships:
              config:
                severity: error
              arguments:
                to: ref('stg_users')
                field: user_id
      - name: total_orders
        tests:
          - not_null
      
  - name: product_sales_summary
    description: Product-level sales summary
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
          - relationships:
              config:
                severity: error
              arguments:
                to: ref('stg_products')
                field: product_id
  
  - name: customer_summary
    description: Customer summary with email domain analysis
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
          - relationships:
              config:
                severity: error
              arguments:
                to: ref('customers')
                field: customer_id